import { FieldDef, SectionDef } from './field-defs';

const depotFields: FieldDef[] = [
  { kind: 'text', key: 'name', label: 'Nome' },
  { kind: 'text', key: 'tagline', label: 'Descrição curta' },
  { kind: 'image', key: 'logoUrl', label: 'Logo', folder: 'logos', hint: 'PNG com fundo transparente fica melhor.' },
  { kind: 'phone', key: 'whatsapp', label: 'WhatsApp' },
  { kind: 'phone', key: 'landline', label: 'Telefone fixo' },
  { kind: 'text', key: 'street', label: 'Rua e número' },
  { kind: 'text', key: 'district', label: 'Bairro' },
  { kind: 'text', key: 'city', label: 'Cidade' },
  { kind: 'text', key: 'zip', label: 'CEP' },
  { kind: 'textarea', key: 'neighborhoods', label: 'Bairros atendidos' },
  { kind: 'text', key: 'instagram', label: 'Instagram (sem @)' },
  { kind: 'url', key: 'mapsUrl', label: 'Link do Google Maps' },
  { kind: 'toggle', key: 'isHeadquarters', label: 'É a matriz', hint: 'Recebe os pedidos quando o cliente não escolhe depósito.' },
  { kind: 'toggle', key: 'selfService24h', label: 'Tem estação de gás 24h' },
];

export const SECTIONS: SectionDef[] = [
  {
    key: 'brand',
    slug: 'geral',
    title: 'Dados gerais',
    description: 'Nome, contatos principais e a frase do rodapé.',
    preview: 'topo',
    fields: [
      { kind: 'text', key: 'groupName', label: 'Nome do grupo' },
      { kind: 'date', key: 'foundedOn', label: 'Data de fundação' },
      { kind: 'text', key: 'city', label: 'Cidade (rodapé)' },
      { kind: 'phone', key: 'landline', label: 'Telefone fixo principal' },
      { kind: 'phone', key: 'whatsapp', label: 'WhatsApp principal' },
      { kind: 'text', key: 'instagram', label: 'Instagram do grupo (sem @)' },
      { kind: 'url', key: 'linktree', label: 'Link da bio (Linktree)' },
      { kind: 'textarea', key: 'footerLine', label: 'Frase grande do rodapé' },
    ],
  },
  {
    key: 'hero',
    slug: 'capa',
    title: 'Capa',
    description: 'O título, o texto de abertura e o vídeo do pátio.',
    preview: 'topo',
    fields: [
      { kind: 'textarea', key: 'title', label: 'Título', hint: 'Curto: até ~40 caracteres fica melhor.' },
      { kind: 'textarea', key: 'lead', label: 'Texto de abertura' },
      { kind: 'video', key: 'videoUrl', label: 'Vídeo do pátio', folder: 'video', hint: 'MP4 horizontal, sem som. Até ~15 MB.' },
      { kind: 'image', key: 'posterUrl', label: 'Imagem antes do vídeo carregar', folder: 'capa' },
    ],
  },
  {
    key: 'hours',
    slug: 'horarios',
    title: 'Horários',
    description: 'Horário da tele-entrega. O site mostra "aberto agora" com base nisto.',
    preview: 'depositos',
    fields: [
      { kind: 'hours', key: 'gas', label: 'Entrega de gás' },
      { kind: 'hours', key: 'agua', label: 'Entrega de água' },
      { kind: 'textarea', key: 'note', label: 'Observação (feriados, 24h…)' },
    ],
  },
  {
    key: 'depots',
    slug: 'depositos',
    title: 'Depósitos',
    description: 'As lojas, com endereço, telefones e bairros atendidos.',
    preview: 'depositos',
    rootList: true,
    fields: [
      {
        kind: 'objectList',
        key: '',
        label: 'Depósitos',
        itemLabel: 'depósito',
        titleKey: 'name',
        fields: depotFields,
        create: () => ({
          id: `dep-${Date.now().toString(36)}`,
          name: 'Novo depósito',
          tagline: '',
          city: '',
          street: '',
          district: '',
          zip: '',
          whatsapp: '',
          landline: '',
          instagram: '',
          mapsUrl: '',
          logoUrl: '',
          neighborhoods: '',
          selfService24h: false,
          isHeadquarters: false,
        }),
      },
    ],
  },
  {
    key: 'gas',
    slug: 'gas',
    title: 'Gás',
    description: 'Tamanhos de botijão, serviços e fotos.',
    preview: 'gas',
    fields: [
      { kind: 'textarea', key: 'title', label: 'Título' },
      { kind: 'textarea', key: 'lead', label: 'Texto' },
      {
        kind: 'objectList',
        key: 'sizes',
        label: 'Botijões',
        itemLabel: 'botijão',
        titleKey: 'code',
        fields: [
          { kind: 'text', key: 'code', label: 'Código (ex.: P13)' },
          { kind: 'text', key: 'kg', label: 'Carga (ex.: 13 kg)' },
          { kind: 'text', key: 'use', label: 'Para que serve' },
        ],
        create: () => ({ code: 'P', kg: '', use: '' }),
      },
      { kind: 'stringList', key: 'services', label: 'Serviços', itemLabel: 'serviço' },
      { kind: 'image', key: 'imageUrl', label: 'Foto grande', folder: 'gas' },
      { kind: 'image', key: 'secondaryImageUrl', label: 'Foto menor', folder: 'gas' },
    ],
  },
  {
    key: 'water',
    slug: 'agua',
    title: 'Água',
    description: 'Marcas, itens e serviços de água mineral.',
    preview: 'agua',
    fields: [
      { kind: 'textarea', key: 'title', label: 'Título' },
      { kind: 'textarea', key: 'lead', label: 'Texto' },
      { kind: 'stringList', key: 'brands', label: 'Marcas', itemLabel: 'marca' },
      { kind: 'stringList', key: 'items', label: 'Itens à venda', itemLabel: 'item' },
      { kind: 'stringList', key: 'services', label: 'Serviços', itemLabel: 'serviço' },
      { kind: 'image', key: 'cutoutUrl', label: 'Galão recortado (PNG/WebP transparente)', folder: 'agua' },
      { kind: 'image', key: 'imageUrl', label: 'Foto', folder: 'agua' },
    ],
  },
  {
    key: 'station',
    slug: 'estacao-24h',
    title: 'Estação 24h',
    description: 'A máquina de autoatendimento. Use "Promoção" para avisos por tempo limitado.',
    preview: 'estacao-24h',
    fields: [
      { kind: 'textarea', key: 'title', label: 'Título' },
      { kind: 'textarea', key: 'lead', label: 'Texto' },
      { kind: 'stringList', key: 'bullets', label: 'Destaques', itemLabel: 'destaque' },
      { kind: 'textarea', key: 'promo', label: 'Promoção (deixe vazio para esconder)', hint: 'Ex.: "Recarga P13 com preço especial na máquina".' },
      { kind: 'text', key: 'address', label: 'Endereço curto' },
      { kind: 'image', key: 'imageUrl', label: 'Imagem da estação', folder: 'estacao' },
    ],
  },
  {
    key: 'safety',
    slug: 'seguranca',
    title: 'Dicas de segurança',
    description: 'As plaquinhas de cuidado com o gás.',
    preview: 'seguranca',
    rootList: true,
    fields: [
      {
        kind: 'objectList',
        key: '',
        label: 'Dicas',
        itemLabel: 'dica',
        titleKey: 'title',
        fields: [
          { kind: 'text', key: 'title', label: 'Título' },
          { kind: 'textarea', key: 'body', label: 'Texto' },
        ],
        create: () => ({ title: 'Nova dica', body: '' }),
      },
    ],
  },
  {
    key: 'about',
    slug: 'sobre',
    title: 'Sobre o grupo',
    description: 'História, depoimento e fotos da equipe.',
    preview: 'sobre',
    fields: [
      { kind: 'textarea', key: 'title', label: 'Título' },
      { kind: 'textarea', key: 'body', label: 'Texto' },
      { kind: 'textarea', key: 'testimonial', label: 'Depoimento de cliente', hint: 'Use só depoimentos reais.' },
      { kind: 'text', key: 'testimonialAuthor', label: 'Quem disse' },
      { kind: 'image', key: 'imageUrl', label: 'Foto 1', folder: 'sobre' },
      { kind: 'image', key: 'secondaryImageUrl', label: 'Foto 2', folder: 'sobre' },
    ],
  },
  {
    key: 'gallery',
    slug: 'fotos',
    title: 'Fotos do dia a dia',
    description: 'A faixa de fotos no fim da página.',
    preview: 'sobre',
    rootList: true,
    fields: [
      {
        kind: 'objectList',
        key: '',
        label: 'Fotos',
        itemLabel: 'foto',
        titleKey: 'alt',
        fields: [
          { kind: 'image', key: 'url', label: 'Foto', folder: 'galeria' },
          { kind: 'text', key: 'alt', label: 'Descrição da foto', hint: 'Para quem usa leitor de tela. Diga o que aparece.' },
        ],
        create: () => ({ url: '', alt: '' }),
      },
    ],
  },
  {
    key: 'faq',
    slug: 'duvidas',
    title: 'Dúvidas',
    description: 'Perguntas e respostas.',
    preview: 'duvidas',
    rootList: true,
    fields: [
      {
        kind: 'objectList',
        key: '',
        label: 'Perguntas',
        itemLabel: 'pergunta',
        titleKey: 'question',
        fields: [
          { kind: 'text', key: 'question', label: 'Pergunta' },
          { kind: 'textarea', key: 'answer', label: 'Resposta' },
        ],
        create: () => ({ question: 'Nova pergunta', answer: '' }),
      },
    ],
  },
  {
    key: 'payments',
    slug: 'pagamento',
    title: 'Formas de pagamento',
    description: 'Listadas no rodapé.',
    rootList: true,
    fields: [{ kind: 'stringList', key: '', label: 'Formas de pagamento', itemLabel: 'forma' }],
  },
];

export const sectionBySlug = (slug: string): SectionDef | undefined => SECTIONS.find((s) => s.slug === slug);
